package io.github.teonistor.adventofcode.y2024

import io.github.teonistor.adventofcode.AdventOfCodeTestBase

class _06Test extends AdventOfCodeTestBase {
  autorun(_06, 41, 6,
    """....#.....
      |.........#
      |..........
      |..#.......
      |.......#..
      |..........
      |.#..^.....
      |........#.
      |#.........
      |......#...
      |""".stripMargin)
}
