package io.github.teonistor.adventofcode.y2022

import io.github.teonistor.adventofcode.AdventOfCodeTestBase

class _10Test extends AdventOfCodeTestBase {
  testAndRun(_10,
    "addx 15\naddx -11\naddx 6\naddx -3\naddx 5\naddx -1\naddx -8\naddx 13\naddx 4\nnoop\naddx -1\naddx 5\naddx -1\naddx 5\naddx -1\naddx 5\naddx -1\naddx 5\naddx -1\naddx -35\naddx 1\naddx 24\naddx -19\naddx 1\naddx 16\naddx -11\nnoop\nnoop\naddx 21\naddx -15\nnoop\nnoop\naddx -3\naddx 9\naddx 1\naddx -3\naddx 8\naddx 1\naddx 5\nnoop\nnoop\nnoop\nnoop\nnoop\naddx -36\nnoop\naddx 1\naddx 7\nnoop\nnoop\nnoop\naddx 2\naddx 6\nnoop\nnoop\nnoop\nnoop\nnoop\naddx 1\nnoop\nnoop\naddx 7\naddx 1\nnoop\naddx -13\naddx 13\naddx 7\nnoop\naddx 1\naddx -33\nnoop\nnoop\nnoop\naddx 2\nnoop\nnoop\nnoop\naddx 8\nnoop\naddx -1\naddx 2\naddx 1\nnoop\naddx 17\naddx -9\naddx 1\naddx 1\naddx -3\naddx 11\nnoop\nnoop\naddx 1\nnoop\naddx 1\nnoop\nnoop\naddx -13\naddx -19\naddx 1\naddx 3\naddx 26\naddx -30\naddx 12\naddx -1\naddx 3\naddx 1\nnoop\nnoop\nnoop\naddx -9\naddx 18\naddx 1\naddx 2\nnoop\nnoop\naddx 9\nnoop\nnoop\nnoop\naddx -1\naddx 2\naddx -37\naddx 1\naddx 3\nnoop\naddx 15\naddx -21\naddx 22\naddx -6\naddx 1\nnoop\naddx 2\naddx 1\nnoop\naddx -10\nnoop\nnoop\naddx 20\naddx 1\naddx 2\naddx 2\naddx -6\naddx -11\nnoop\nnoop\nnoop",
    "13140",
    "##..##..##..##..##..##..##..##..##..##..\n###...###...###...###...###...###...###.\n####....####....####....####....####....\n#####.....#####.....#####.....#####.....\n######......######......######......####\n#######.......#######.......#######.....",
    "noop\nnoop\naddx 5\naddx 31\naddx -30\naddx 2\naddx 7\nnoop\nnoop\naddx -4\naddx 5\naddx 6\nnoop\naddx -1\naddx 5\naddx -1\naddx 5\naddx 1\nnoop\naddx 5\nnoop\naddx -1\naddx -35\naddx 3\nnoop\naddx 2\naddx 3\naddx -2\naddx 2\nnoop\naddx 8\naddx -3\naddx 5\naddx -17\naddx 22\naddx -2\naddx 2\naddx 5\naddx -2\naddx -26\naddx 31\naddx 2\naddx 5\naddx -40\naddx 30\naddx -27\naddx 4\naddx 2\naddx 3\naddx -3\naddx 8\nnoop\nnoop\naddx 2\naddx 21\naddx -15\naddx -2\naddx 2\nnoop\naddx 15\naddx -16\naddx 8\nnoop\naddx 3\naddx 5\naddx -38\nnoop\nnoop\nnoop\naddx 5\naddx -5\naddx 6\naddx 2\naddx 7\nnoop\nnoop\naddx 4\naddx -3\nnoop\nnoop\naddx 7\naddx 2\naddx 2\naddx -1\nnoop\naddx 3\naddx 6\nnoop\naddx 1\nnoop\nnoop\naddx -38\nnoop\nnoop\naddx 7\naddx 3\nnoop\naddx 2\naddx -2\naddx 7\naddx -2\naddx 5\naddx 2\naddx 5\naddx -4\naddx 2\naddx 5\naddx 2\naddx -21\naddx 9\naddx 15\nnoop\naddx 3\naddx -38\naddx 7\nnoop\nnoop\naddx 18\naddx -17\naddx 4\nnoop\naddx 1\naddx 2\naddx 5\naddx 3\nnoop\nnoop\naddx 14\naddx -9\nnoop\nnoop\naddx 4\naddx 1\nnoop\naddx 4\naddx 3\nnoop\naddx -8\nnoop"
  )
}