package io.github.teonistor.mpmp;

import io.vavr.collection.List;
import io.vavr.collection.Stream;
import lombok.AllArgsConstructor;

import java.util.ArrayList;
import java.util.function.Consumer;

import static io.github.teonistor.mpmp.Orientation.Flipped;
import static io.github.teonistor.mpmp.Orientation.Mirror;
import static io.github.teonistor.mpmp.Orientation.Normal;
import static io.github.teonistor.mpmp.Orientation.UpsideDown;
import static java.util.stream.Collectors.joining;

public class StackFold {

    public static void main(String[] arg) {

        ArrayList<List<Orientation>> allStacks = new ArrayList<>();
        final List<Orientation> odd = List.of(Normal, UpsideDown, UpsideDown);
        final List<Orientation> even = List.of(Mirror, Mirror, Flipped, Flipped);
        buildStacks(List.of(Normal), even, odd, allStacks::add);

        final Stream<List<Rect>> uniqueStacks = Stream.ofAll(allStacks).distinct().map(stack -> stack.map(Rect::new));

        final ArrayList<List<Rect>> solutions = new ArrayList<>();
        uniqueStacks.forEach(stack -> hingeBottom(stack, 0, 4, 4, 2, solutions::add));

        final List<String> distinct = Stream.ofAll(solutions).map(StackFold::explicitate).filter(str -> !str.isEmpty()).distinct().toList();
        distinct.forEach(System.out::println);
        System.out.println("Total explicit: " + distinct.size());
        System.out.println("Total raw: " + solutions.size());

//        go(List.of(new FirstRect(), new Rect(), new Rect(), new Rect(), new Rect(), new Rect(), new Rect(), new Rect()),
//                0, 6, 4);
    }

    static void buildStacks(List<Orientation> currentStack, List<Orientation> nextPick, List<Orientation> otherPick, Consumer<List<Orientation>> consumer) {
        if (currentStack.size() == 8) {
            consumer.accept(currentStack);
            return;
        }

        for (int i = 0; i < nextPick.size(); i++) {
            buildStacks(currentStack.append(nextPick.get(i)), otherPick, nextPick.removeAt(i), consumer);
        }
    }

    static void hingeBottom(List<Rect> stack, int index, int bottomsLeft, int rightsLeft, int leftsLeft, Consumer<List<Rect>> consumer) {
        if (index == 8) {
            if (bottomsLeft + rightsLeft + leftsLeft == 0) {
                consumer.accept(stack);
            }
            return;
        }

//        final String mnemo = stack.toJavaStream()
//                .map(rect -> rect.orientation.toString().substring(0, 1))
//                .collect(joining());
//        final String ffs = mnemo;

        final Rect thisRect = stack.get(index);
        if (thisRect.bottom < 0) {
            if (bottomsLeft > 0) {
                for (int thatIndex = index + 1; thatIndex < 8; thatIndex++) {
                    final Rect thatRect = stack.get(thatIndex);
                    if (thatRect.bottom < 0) {
                        hingeRight(stack.update(index, thisRect.hingeBottom(thatIndex)).update(thatIndex, thatRect.hingeBottom(index)),
                                index, bottomsLeft - 1, rightsLeft, leftsLeft, consumer);
                    } else {
                        break;
                    }
                }
            }

        } else {
            hingeRight(stack, index, bottomsLeft, rightsLeft, leftsLeft, consumer);
        }
    }

    static void hingeRight(List<Rect> stack, int index, int bottomsLeft, int rightsLeft, int leftsLeft, Consumer<List<Rect>> consumer) {
        final Rect thisRect = stack.get(index);
        if (thisRect.right < 0) {
            if (rightsLeft > 0) {
                for (int thatIndex = index + 1; thatIndex < 8; thatIndex++) {
                    final Rect thatRect = stack.get(thatIndex);
                    if (thatRect.right < 0) {

                        // Left hinge is optional so we make one call going to the next item in the stack and one adding another hinge
                        final List<Rect> newStack = stack.update(index, thisRect.hingeRight(thatIndex)).update(thatIndex, thatRect.hingeRight(index));
                        hingeBottom(newStack, index + 1, bottomsLeft, rightsLeft - 1, leftsLeft, consumer);
                        hingeLeft(newStack, index, bottomsLeft, rightsLeft - 1, leftsLeft, consumer);
                    } else {
                        break;
                    }
                }
            }

        } else {
            // Left hinge is optional so we make one call going to the next item in the stack and one adding another hinge
            hingeBottom(stack, index+1, bottomsLeft, rightsLeft, leftsLeft, consumer);
            hingeLeft(stack, index, bottomsLeft, rightsLeft, leftsLeft, consumer);
        }
    }

    static void hingeLeft(List<Rect> stack, int index, int bottomsLeft, int rightsLeft, int leftsLeft, Consumer<List<Rect>> consumer) {
        // "A" never has left hinge
        if (index == 0) {
            return;
        }

        final Rect thisRect = stack.get(index);
        if (thisRect.left < 0) {
            if (rightsLeft > 0) {
                for (int thatIndex = index + 1; thatIndex < 8; thatIndex++) {
                    final Rect thatRect = stack.get(thatIndex);
                    if (thatRect.left < 0) {
                        hingeBottom(stack.update(index, thisRect.hingeLeft(thatIndex)).update(thatIndex, thatRect.hingeLeft(index)),
                                index + 1, bottomsLeft, rightsLeft, leftsLeft - 1, consumer);
                    } else {
                        break;
                    }
                }
            }

        } else {
            // Actually this would create duplicates because left hinge is optional
//            hingeBottom(stack, index+1, bottomsLeft, rightsLeft, leftsLeft, consumer);
        }
    }

    static String explicitate(List<Rect> stack) {
        final String mnemo = stack.toJavaStream()
                .map(rect -> rect.orientation.toString().substring(0, 1))
                .collect(joining());


        final Rect m = stack.get(0);
        final Rect n = stack.get(m.right);
        if (n.left < 0) {
            System.err.println("Explicitate bail because n had no left");
            return "";
        }
        final Rect o = stack.get(n.left);
        final Rect p = stack.get(o.right);

        final Rect q = stack.get(m.bottom);
        final Rect r = stack.get(q.right);
        if (r.left < 0) {
            System.err.println("Explicitate bail because r had no left");
            return "";
        }
        final Rect s = stack.get(r.left);
        final Rect t = stack.get(s.right);

        if (stack.get(n.bottom) != r
         || stack.get(o.bottom) != s
         || stack.get(p.bottom) != t) {
            System.err.println("Explicitate bail because the small hinges did not match");
            return "";
        }

        final List<Rect> m1 = List.of(m, n, o, p, q, r, s, t);
        return m1.toJavaStream()
                 .mapToInt(stack::indexOf)
                 .mapToObj(i -> "" + (char)('A' + i))
                 .collect(joining())
                + " / " +
                 mnemo;
    }

}

enum Orientation {
    Normal, Mirror, Flipped, UpsideDown;

    private Orientation flip, mirror;

    public Orientation flip() {
        return flip;
    }

    public Orientation mirror() {
        return mirror;
    }

    static {
        Normal    .flip   = Flipped;
        Normal    .mirror = Mirror;
        Mirror    .flip   = UpsideDown;
        Mirror    .mirror = Normal;
        Flipped   .flip   = Normal;
        Flipped   .mirror = UpsideDown;
        UpsideDown.flip   = Mirror;
        UpsideDown.mirror = Flipped;
    }
}

@AllArgsConstructor
class Rect {
    final Orientation orientation;
    final int bottom, right, left;

    public Rect(Orientation orientation) {
        this(orientation, -1, -1, -1);
    }

    public Rect hingeBottom(int index) {
        invariantNegative(bottom, "bottom");
        return new Rect(orientation, index, right, left);
    }

    public Rect hingeRight(int index) {
        invariantNegative(right, "right");
        return new Rect(orientation, bottom, index, left);
    }

    public Rect hingeLeft(int index) {
        invariantNegative(left, "left");
        return new Rect(orientation, bottom, right, index);
    }

    private void invariantNegative(int index, String side) {
        if (index >= 0) {
            System.err.printf("Rect: Invariant violation! Hinging %s on already hinged %s%n", side, side);
        }
    }
}

/***********************
 With mnemo included:
 ADCBBCDA / NMNMUFUF
 ADEFBCFE / NMNMUFUF
 ADEHBCFG / NMNMUFUF
 ADFEBCGH / NMNMUFUF
 ADFGBCGF / NMNMUFUF
 ADEFBCHG / NMNMUFUF
 ADEHBCHE / NMNMUFUF
 ADGHBCHG / NMNMUFUF
 ADGFBCHE / NMNMUFUF
 AFEDBCDE / NMNMUFUF
 AFCBBCFA / NMNMUFUF
 AFGHBCHG / NMNMUFUF
 AFGHBEHG / NMNMUFUF
 AFEBBEFA / NMNMUFUF
 AFCDBEDC / NMNMUFUF
 AFGHBEDC / NMNMUFUF
 AFHGBECD / NMNMUFUF
 AHEDBCDE / NMNMUFUF
 AHCBBCHA / NMNMUFUF
 AHEBBEHA / NMNMUFUF
 AHCDBEDC / NMNMUFUF
 AHCDBGDC / NMNMUFUF
 ABCDDCBA / NMNMUFUF
 ABFEDCEF / NMNMUFUF
 ABFGDCEH / NMNMUFUF
 ABGHDCFE / NMNMUFUF
 ABGFDCFG / NMNMUFUF
 ABHGDCEF / NMNMUFUF
 ABHEDCEH / NMNMUFUF
 ABHGDCGH / NMNMUFUF
 ABHEDCGF / NMNMUFUF
 AFGHDEHG / NMNMUFUF
 AFEDDEFA / NMNMUFUF
 AFBCDECB / NMNMUFUF
 AHEDDEHA / NMNMUFUF
 AHBCDECB / NMNMUFUF
 AHBCDGCB / NMNMUFUF
 AHBGDECF / NMNMUFUF
 ABCFFCBA / NMNMUFUF
 ABEDFCDE / NMNMUFUF
 ABHGFCGH / NMNMUFUF
 ABCDFEDC / NMNMUFUF
 ABCHFEDG / NMNMUFUF
 ABEFFEBA / NMNMUFUF
 ABHGFEGH / NMNMUFUF
 ADEFFEDA / NMNMUFUF
 ADHGFEGH / NMNMUFUF
 ADCBFEBC / NMNMUFUF
 AHDEFGED / NMNMUFUF
 AHBCFGCB / NMNMUFUF
 AHDCFGEB / NMNMUFUF
 AHBEFGCD / NMNMUFUF
 AHCBFGDE / NMNMUFUF
 AHBCFGED / NMNMUFUF
 AHCDFGDC / NMNMUFUF
 AHBEFGEB / NMNMUFUF
 ABCHHCBA / NMNMUFUF
 ABEDHCDE / NMNMUFUF
 ABEFHCDG / NMNMUFUF
 ABFGHCED / NMNMUFUF
 ABFEHCEF / NMNMUFUF
 ABGFHCDE / NMNMUFUF
 ABGDHCDG / NMNMUFUF
 ABGFHCFG / NMNMUFUF
 ABGDHCFE / NMNMUFUF
 ABCDHEDC / NMNMUFUF
 ABEHHEBA / NMNMUFUF
 ABGFHEFG / NMNMUFUF
 ABCDHGDC / NMNMUFUF
 ABCFHGDE / NMNMUFUF
 ABCDHGFE / NMNMUFUF
 ABCFHGFC / NMNMUFUF
 ABDCHGEF / NMNMUFUF
 ABDEHGED / NMNMUFUF
 ABEFHGFE / NMNMUFUF
 ABEDHGFC / NMNMUFUF
 ABGHHGBA / NMNMUFUF
 ADGFHEFG / NMNMUFUF
 ADEFHGFE / NMNMUFUF
 ADGHHGDA / NMNMUFUF
 ADEHHEDA / NMNMUFUF
 ADCBHEBC / NMNMUFUF
 ADCBHGBC / NMNMUFUF
 ADCBHEFG / NMNMUFUF
 ADBCHEGF / NMNMUFUF
 AFGHHGFA / NMNMUFUF
 AFEDHGDE / NMNMUFUF
 AFCBHGBC / NMNMUFUF
 AFEBHGDC / NMNMUFUF
 AFCDHGBE / NMNMUFUF
 AFDEHGCB / NMNMUFUF
 AFEDHGBC / NMNMUFUF
 AFDCHGCD / NMNMUFUF
 AFEBHGBE / NMNMUFUF
 ADCBBCDA / NMNFUMUF
 ADEFBCFE / NMNFUMUF
 ADEHBCFG / NMNFUMUF
 ADFEBCGH / NMNFUMUF
 ADFGBCGF / NMNFUMUF
 ADEFBCHG / NMNFUMUF
 ADEHBCHE / NMNFUMUF
 ADGHBCHG / NMNFUMUF
 ADGFBCHE / NMNFUMUF
 AFEDBCDE / NMNFUMUF
 AFCBBCFA / NMNFUMUF
 AFGHBCHG / NMNFUMUF
 AFGHBEHG / NMNFUMUF
 AFEBBEFA / NMNFUMUF
 AFCDBEDC / NMNFUMUF
 AFGHBEDC / NMNFUMUF
 AFHGBECD / NMNFUMUF
 AHEDBCDE / NMNFUMUF
 AHCBBCHA / NMNFUMUF
 AHEBBEHA / NMNFUMUF
 AHCDBEDC / NMNFUMUF
 AHCDBGDC / NMNFUMUF
 ABCDDCBA / NMNFUMUF
 ABFEDCEF / NMNFUMUF
 ABFGDCEH / NMNFUMUF
 ABGHDCFE / NMNFUMUF
 ABGFDCFG / NMNFUMUF
 ABHGDCEF / NMNFUMUF
 ABHEDCEH / NMNFUMUF
 ABHGDCGH / NMNFUMUF
 ABHEDCGF / NMNFUMUF
 AFGHDEHG / NMNFUMUF
 AFEDDEFA / NMNFUMUF
 AFBCDECB / NMNFUMUF
 AHEDDEHA / NMNFUMUF
 AHBCDECB / NMNFUMUF
 AHBCDGCB / NMNFUMUF
 AHBGDECF / NMNFUMUF
 ABCFFCBA / NMNFUMUF
 ABEDFCDE / NMNFUMUF
 ABHGFCGH / NMNFUMUF
 ABCDFEDC / NMNFUMUF
 ABCHFEDG / NMNFUMUF
 ABEFFEBA / NMNFUMUF
 ABHGFEGH / NMNFUMUF
 ADEFFEDA / NMNFUMUF
 ADHGFEGH / NMNFUMUF
 ADCBFEBC / NMNFUMUF
 AHDEFGED / NMNFUMUF
 AHBCFGCB / NMNFUMUF
 AHDCFGEB / NMNFUMUF
 AHBEFGCD / NMNFUMUF
 AHCBFGDE / NMNFUMUF
 AHBCFGED / NMNFUMUF
 AHCDFGDC / NMNFUMUF
 AHBEFGEB / NMNFUMUF
 ABCHHCBA / NMNFUMUF
 ABEDHCDE / NMNFUMUF
 ABEFHCDG / NMNFUMUF
 ABFGHCED / NMNFUMUF
 ABFEHCEF / NMNFUMUF
 ABGFHCDE / NMNFUMUF
 ABGDHCDG / NMNFUMUF
 ABGFHCFG / NMNFUMUF
 ABGDHCFE / NMNFUMUF
 ABCDHEDC / NMNFUMUF
 ABEHHEBA / NMNFUMUF
 ABGFHEFG / NMNFUMUF
 ABCDHGDC / NMNFUMUF
 ABCFHGDE / NMNFUMUF
 ABCDHGFE / NMNFUMUF
 ABCFHGFC / NMNFUMUF
 ABDCHGEF / NMNFUMUF
 ABDEHGED / NMNFUMUF
 ABEFHGFE / NMNFUMUF
 ABEDHGFC / NMNFUMUF
 ABGHHGBA / NMNFUMUF
 ADGFHEFG / NMNFUMUF
 ADEFHGFE / NMNFUMUF
 ADGHHGDA / NMNFUMUF
 ADEHHEDA / NMNFUMUF
 ADCBHEBC / NMNFUMUF
 ADCBHGBC / NMNFUMUF
 ADCBHEFG / NMNFUMUF
 ADBCHEGF / NMNFUMUF
 AFGHHGFA / NMNFUMUF
 AFEDHGDE / NMNFUMUF
 AFCBHGBC / NMNFUMUF
 AFEBHGDC / NMNFUMUF
 AFCDHGBE / NMNFUMUF
 AFDEHGCB / NMNFUMUF
 AFEDHGBC / NMNFUMUF
 AFDCHGCD / NMNFUMUF
 AFEBHGBE / NMNFUMUF
 ADCBBCDA / NMNFUFUM
 ADEFBCFE / NMNFUFUM
 ADEHBCFG / NMNFUFUM
 ADFEBCGH / NMNFUFUM
 ADFGBCGF / NMNFUFUM
 ADEFBCHG / NMNFUFUM
 ADEHBCHE / NMNFUFUM
 ADGHBCHG / NMNFUFUM
 ADGFBCHE / NMNFUFUM
 AFEDBCDE / NMNFUFUM
 AFCBBCFA / NMNFUFUM
 AFGHBCHG / NMNFUFUM
 AFGHBEHG / NMNFUFUM
 AFEBBEFA / NMNFUFUM
 AFCDBEDC / NMNFUFUM
 AFGHBEDC / NMNFUFUM
 AFHGBECD / NMNFUFUM
 AHEDBCDE / NMNFUFUM
 AHCBBCHA / NMNFUFUM
 AHEBBEHA / NMNFUFUM
 AHCDBEDC / NMNFUFUM
 AHCDBGDC / NMNFUFUM
 ABCDDCBA / NMNFUFUM
 ABFEDCEF / NMNFUFUM
 ABFGDCEH / NMNFUFUM
 ABGHDCFE / NMNFUFUM
 ABGFDCFG / NMNFUFUM
 ABHGDCEF / NMNFUFUM
 ABHEDCEH / NMNFUFUM
 ABHGDCGH / NMNFUFUM
 ABHEDCGF / NMNFUFUM
 AFGHDEHG / NMNFUFUM
 AFEDDEFA / NMNFUFUM
 AFBCDECB / NMNFUFUM
 AHEDDEHA / NMNFUFUM
 AHBCDECB / NMNFUFUM
 AHBCDGCB / NMNFUFUM
 AHBGDECF / NMNFUFUM
 ABCFFCBA / NMNFUFUM
 ABEDFCDE / NMNFUFUM
 ABHGFCGH / NMNFUFUM
 ABCDFEDC / NMNFUFUM
 ABCHFEDG / NMNFUFUM
 ABEFFEBA / NMNFUFUM
 ABHGFEGH / NMNFUFUM
 ADEFFEDA / NMNFUFUM
 ADHGFEGH / NMNFUFUM
 ADCBFEBC / NMNFUFUM
 AHDEFGED / NMNFUFUM
 AHBCFGCB / NMNFUFUM
 AHDCFGEB / NMNFUFUM
 AHBEFGCD / NMNFUFUM
 AHCBFGDE / NMNFUFUM
 AHBCFGED / NMNFUFUM
 AHCDFGDC / NMNFUFUM
 AHBEFGEB / NMNFUFUM
 ABCHHCBA / NMNFUFUM
 ABEDHCDE / NMNFUFUM
 ABEFHCDG / NMNFUFUM
 ABFGHCED / NMNFUFUM
 ABFEHCEF / NMNFUFUM
 ABGFHCDE / NMNFUFUM
 ABGDHCDG / NMNFUFUM
 ABGFHCFG / NMNFUFUM
 ABGDHCFE / NMNFUFUM
 ABCDHEDC / NMNFUFUM
 ABEHHEBA / NMNFUFUM
 ABGFHEFG / NMNFUFUM
 ABCDHGDC / NMNFUFUM
 ABCFHGDE / NMNFUFUM
 ABCDHGFE / NMNFUFUM
 ABCFHGFC / NMNFUFUM
 ABDCHGEF / NMNFUFUM
 ABDEHGED / NMNFUFUM
 ABEFHGFE / NMNFUFUM
 ABEDHGFC / NMNFUFUM
 ABGHHGBA / NMNFUFUM
 ADGFHEFG / NMNFUFUM
 ADEFHGFE / NMNFUFUM
 ADGHHGDA / NMNFUFUM
 ADEHHEDA / NMNFUFUM
 ADCBHEBC / NMNFUFUM
 ADCBHGBC / NMNFUFUM
 ADCBHEFG / NMNFUFUM
 ADBCHEGF / NMNFUFUM
 AFGHHGFA / NMNFUFUM
 AFEDHGDE / NMNFUFUM
 AFCBHGBC / NMNFUFUM
 AFEBHGDC / NMNFUFUM
 AFCDHGBE / NMNFUFUM
 AFDEHGCB / NMNFUFUM
 AFEDHGBC / NMNFUFUM
 AFDCHGCD / NMNFUFUM
 AFEBHGBE / NMNFUFUM
 ADCBBCDA / NMUMNFUF
 ADEFBCFE / NMUMNFUF
 ADEHBCFG / NMUMNFUF
 ADFEBCGH / NMUMNFUF
 ADFGBCGF / NMUMNFUF
 ADEFBCHG / NMUMNFUF
 ADEHBCHE / NMUMNFUF
 ADGHBCHG / NMUMNFUF
 ADGFBCHE / NMUMNFUF
 AFEDBCDE / NMUMNFUF
 AFCBBCFA / NMUMNFUF
 AFGHBCHG / NMUMNFUF
 AFGHBEHG / NMUMNFUF
 AFEBBEFA / NMUMNFUF
 AFCDBEDC / NMUMNFUF
 AFGHBEDC / NMUMNFUF
 AFHGBECD / NMUMNFUF
 AHEDBCDE / NMUMNFUF
 AHCBBCHA / NMUMNFUF
 AHEBBEHA / NMUMNFUF
 AHCDBEDC / NMUMNFUF
 AHCDBGDC / NMUMNFUF
 ABCDDCBA / NMUMNFUF
 ABFEDCEF / NMUMNFUF
 ABFGDCEH / NMUMNFUF
 ABGHDCFE / NMUMNFUF
 ABGFDCFG / NMUMNFUF
 ABHGDCEF / NMUMNFUF
 ABHEDCEH / NMUMNFUF
 ABHGDCGH / NMUMNFUF
 ABHEDCGF / NMUMNFUF
 AFGHDEHG / NMUMNFUF
 AFEDDEFA / NMUMNFUF
 AFBCDECB / NMUMNFUF
 AHEDDEHA / NMUMNFUF
 AHBCDECB / NMUMNFUF
 AHBCDGCB / NMUMNFUF
 AHBGDECF / NMUMNFUF
 ABCFFCBA / NMUMNFUF
 ABEDFCDE / NMUMNFUF
 ABHGFCGH / NMUMNFUF
 ABCDFEDC / NMUMNFUF
 ABCHFEDG / NMUMNFUF
 ABEFFEBA / NMUMNFUF
 ABHGFEGH / NMUMNFUF
 ADEFFEDA / NMUMNFUF
 ADHGFEGH / NMUMNFUF
 ADCBFEBC / NMUMNFUF
 AHDEFGED / NMUMNFUF
 AHBCFGCB / NMUMNFUF
 AHDCFGEB / NMUMNFUF
 AHBEFGCD / NMUMNFUF
 AHCBFGDE / NMUMNFUF
 AHBCFGED / NMUMNFUF
 AHCDFGDC / NMUMNFUF
 AHBEFGEB / NMUMNFUF
 ABCHHCBA / NMUMNFUF
 ABEDHCDE / NMUMNFUF
 ABEFHCDG / NMUMNFUF
 ABFGHCED / NMUMNFUF
 ABFEHCEF / NMUMNFUF
 ABGFHCDE / NMUMNFUF
 ABGDHCDG / NMUMNFUF
 ABGFHCFG / NMUMNFUF
 ABGDHCFE / NMUMNFUF
 ABCDHEDC / NMUMNFUF
 ABEHHEBA / NMUMNFUF
 ABGFHEFG / NMUMNFUF
 ABCDHGDC / NMUMNFUF
 ABCFHGDE / NMUMNFUF
 ABCDHGFE / NMUMNFUF
 ABCFHGFC / NMUMNFUF
 ABDCHGEF / NMUMNFUF
 ABDEHGED / NMUMNFUF
 ABEFHGFE / NMUMNFUF
 ABEDHGFC / NMUMNFUF
 ABGHHGBA / NMUMNFUF
 ADGFHEFG / NMUMNFUF
 ADEFHGFE / NMUMNFUF
 ADGHHGDA / NMUMNFUF
 ADEHHEDA / NMUMNFUF
 ADCBHEBC / NMUMNFUF
 ADCBHGBC / NMUMNFUF
 ADCBHEFG / NMUMNFUF
 ADBCHEGF / NMUMNFUF
 AFGHHGFA / NMUMNFUF
 AFEDHGDE / NMUMNFUF
 AFCBHGBC / NMUMNFUF
 AFEBHGDC / NMUMNFUF
 AFCDHGBE / NMUMNFUF
 AFDEHGCB / NMUMNFUF
 AFEDHGBC / NMUMNFUF
 AFDCHGCD / NMUMNFUF
 AFEBHGBE / NMUMNFUF
 ADCBBCDA / NMUMUFNF
 ADEFBCFE / NMUMUFNF
 ADEHBCFG / NMUMUFNF
 ADFEBCGH / NMUMUFNF
 ADFGBCGF / NMUMUFNF
 ADEFBCHG / NMUMUFNF
 ADEHBCHE / NMUMUFNF
 ADGHBCHG / NMUMUFNF
 ADGFBCHE / NMUMUFNF
 AFEDBCDE / NMUMUFNF
 AFCBBCFA / NMUMUFNF
 AFGHBCHG / NMUMUFNF
 AFGHBEHG / NMUMUFNF
 AFEBBEFA / NMUMUFNF
 AFCDBEDC / NMUMUFNF
 AFGHBEDC / NMUMUFNF
 AFHGBECD / NMUMUFNF
 AHEDBCDE / NMUMUFNF
 AHCBBCHA / NMUMUFNF
 AHEBBEHA / NMUMUFNF
 AHCDBEDC / NMUMUFNF
 AHCDBGDC / NMUMUFNF
 ABCDDCBA / NMUMUFNF
 ABFEDCEF / NMUMUFNF
 ABFGDCEH / NMUMUFNF
 ABGHDCFE / NMUMUFNF
 ABGFDCFG / NMUMUFNF
 ABHGDCEF / NMUMUFNF
 ABHEDCEH / NMUMUFNF
 ABHGDCGH / NMUMUFNF
 ABHEDCGF / NMUMUFNF
 AFGHDEHG / NMUMUFNF
 AFEDDEFA / NMUMUFNF
 AFBCDECB / NMUMUFNF
 AHEDDEHA / NMUMUFNF
 AHBCDECB / NMUMUFNF
 AHBCDGCB / NMUMUFNF
 AHBGDECF / NMUMUFNF
 ABCFFCBA / NMUMUFNF
 ABEDFCDE / NMUMUFNF
 ABHGFCGH / NMUMUFNF
 ABCDFEDC / NMUMUFNF
 ABCHFEDG / NMUMUFNF
 ABEFFEBA / NMUMUFNF
 ABHGFEGH / NMUMUFNF
 ADEFFEDA / NMUMUFNF
 ADHGFEGH / NMUMUFNF
 ADCBFEBC / NMUMUFNF
 AHDEFGED / NMUMUFNF
 AHBCFGCB / NMUMUFNF
 AHDCFGEB / NMUMUFNF
 AHBEFGCD / NMUMUFNF
 AHCBFGDE / NMUMUFNF
 AHBCFGED / NMUMUFNF
 AHCDFGDC / NMUMUFNF
 AHBEFGEB / NMUMUFNF
 ABCHHCBA / NMUMUFNF
 ABEDHCDE / NMUMUFNF
 ABEFHCDG / NMUMUFNF
 ABFGHCED / NMUMUFNF
 ABFEHCEF / NMUMUFNF
 ABGFHCDE / NMUMUFNF
 ABGDHCDG / NMUMUFNF
 ABGFHCFG / NMUMUFNF
 ABGDHCFE / NMUMUFNF
 ABCDHEDC / NMUMUFNF
 ABEHHEBA / NMUMUFNF
 ABGFHEFG / NMUMUFNF
 ABCDHGDC / NMUMUFNF
 ABCFHGDE / NMUMUFNF
 ABCDHGFE / NMUMUFNF
 ABCFHGFC / NMUMUFNF
 ABDCHGEF / NMUMUFNF
 ABDEHGED / NMUMUFNF
 ABEFHGFE / NMUMUFNF
 ABEDHGFC / NMUMUFNF
 ABGHHGBA / NMUMUFNF
 ADGFHEFG / NMUMUFNF
 ADEFHGFE / NMUMUFNF
 ADGHHGDA / NMUMUFNF
 ADEHHEDA / NMUMUFNF
 ADCBHEBC / NMUMUFNF
 ADCBHGBC / NMUMUFNF
 ADCBHEFG / NMUMUFNF
 ADBCHEGF / NMUMUFNF
 AFGHHGFA / NMUMUFNF
 AFEDHGDE / NMUMUFNF
 AFCBHGBC / NMUMUFNF
 AFEBHGDC / NMUMUFNF
 AFCDHGBE / NMUMUFNF
 AFDEHGCB / NMUMUFNF
 AFEDHGBC / NMUMUFNF
 AFDCHGCD / NMUMUFNF
 AFEBHGBE / NMUMUFNF
 ADCBBCDA / NMUFNMUF
 ADEFBCFE / NMUFNMUF
 ADEHBCFG / NMUFNMUF
 ADFEBCGH / NMUFNMUF
 ADFGBCGF / NMUFNMUF
 ADEFBCHG / NMUFNMUF
 ADEHBCHE / NMUFNMUF
 ADGHBCHG / NMUFNMUF
 ADGFBCHE / NMUFNMUF
 AFEDBCDE / NMUFNMUF
 AFCBBCFA / NMUFNMUF
 AFGHBCHG / NMUFNMUF
 AFGHBEHG / NMUFNMUF
 AFEBBEFA / NMUFNMUF
 AFCDBEDC / NMUFNMUF
 AFGHBEDC / NMUFNMUF
 AFHGBECD / NMUFNMUF
 AHEDBCDE / NMUFNMUF
 AHCBBCHA / NMUFNMUF
 AHEBBEHA / NMUFNMUF
 AHCDBEDC / NMUFNMUF
 AHCDBGDC / NMUFNMUF
 ABCDDCBA / NMUFNMUF
 ABFEDCEF / NMUFNMUF
 ABFGDCEH / NMUFNMUF
 ABGHDCFE / NMUFNMUF
 ABGFDCFG / NMUFNMUF
 ABHGDCEF / NMUFNMUF
 ABHEDCEH / NMUFNMUF
 ABHGDCGH / NMUFNMUF
 ABHEDCGF / NMUFNMUF
 AFGHDEHG / NMUFNMUF
 AFEDDEFA / NMUFNMUF
 AFBCDECB / NMUFNMUF
 AHEDDEHA / NMUFNMUF
 AHBCDECB / NMUFNMUF
 AHBCDGCB / NMUFNMUF
 AHBGDECF / NMUFNMUF
 ABCFFCBA / NMUFNMUF
 ABEDFCDE / NMUFNMUF
 ABHGFCGH / NMUFNMUF
 ABCDFEDC / NMUFNMUF
 ABCHFEDG / NMUFNMUF
 ABEFFEBA / NMUFNMUF
 ABHGFEGH / NMUFNMUF
 ADEFFEDA / NMUFNMUF
 ADHGFEGH / NMUFNMUF
 ADCBFEBC / NMUFNMUF
 AHDEFGED / NMUFNMUF
 AHBCFGCB / NMUFNMUF
 AHDCFGEB / NMUFNMUF
 AHBEFGCD / NMUFNMUF
 AHCBFGDE / NMUFNMUF
 AHBCFGED / NMUFNMUF
 AHCDFGDC / NMUFNMUF
 AHBEFGEB / NMUFNMUF
 ABCHHCBA / NMUFNMUF
 ABEDHCDE / NMUFNMUF
 ABEFHCDG / NMUFNMUF
 ABFGHCED / NMUFNMUF
 ABFEHCEF / NMUFNMUF
 ABGFHCDE / NMUFNMUF
 ABGDHCDG / NMUFNMUF
 ABGFHCFG / NMUFNMUF
 ABGDHCFE / NMUFNMUF
 ABCDHEDC / NMUFNMUF
 ABEHHEBA / NMUFNMUF
 ABGFHEFG / NMUFNMUF
 ABCDHGDC / NMUFNMUF
 ABCFHGDE / NMUFNMUF
 ABCDHGFE / NMUFNMUF
 ABCFHGFC / NMUFNMUF
 ABDCHGEF / NMUFNMUF
 ABDEHGED / NMUFNMUF
 ABEFHGFE / NMUFNMUF
 ABEDHGFC / NMUFNMUF
 ABGHHGBA / NMUFNMUF
 ADGFHEFG / NMUFNMUF
 ADEFHGFE / NMUFNMUF
 ADGHHGDA / NMUFNMUF
 ADEHHEDA / NMUFNMUF
 ADCBHEBC / NMUFNMUF
 ADCBHGBC / NMUFNMUF
 ADCBHEFG / NMUFNMUF
 ADBCHEGF / NMUFNMUF
 AFGHHGFA / NMUFNMUF
 AFEDHGDE / NMUFNMUF
 AFCBHGBC / NMUFNMUF
 AFEBHGDC / NMUFNMUF
 AFCDHGBE / NMUFNMUF
 AFDEHGCB / NMUFNMUF
 AFEDHGBC / NMUFNMUF
 AFDCHGCD / NMUFNMUF
 AFEBHGBE / NMUFNMUF
 ADCBBCDA / NMUFNFUM
 ADEFBCFE / NMUFNFUM
 ADEHBCFG / NMUFNFUM
 ADFEBCGH / NMUFNFUM
 ADFGBCGF / NMUFNFUM
 ADEFBCHG / NMUFNFUM
 ADEHBCHE / NMUFNFUM
 ADGHBCHG / NMUFNFUM
 ADGFBCHE / NMUFNFUM
 AFEDBCDE / NMUFNFUM
 AFCBBCFA / NMUFNFUM
 AFGHBCHG / NMUFNFUM
 AFGHBEHG / NMUFNFUM
 AFEBBEFA / NMUFNFUM
 AFCDBEDC / NMUFNFUM
 AFGHBEDC / NMUFNFUM
 AFHGBECD / NMUFNFUM
 AHEDBCDE / NMUFNFUM
 AHCBBCHA / NMUFNFUM
 AHEBBEHA / NMUFNFUM
 AHCDBEDC / NMUFNFUM
 AHCDBGDC / NMUFNFUM
 ABCDDCBA / NMUFNFUM
 ABFEDCEF / NMUFNFUM
 ABFGDCEH / NMUFNFUM
 ABGHDCFE / NMUFNFUM
 ABGFDCFG / NMUFNFUM
 ABHGDCEF / NMUFNFUM
 ABHEDCEH / NMUFNFUM
 ABHGDCGH / NMUFNFUM
 ABHEDCGF / NMUFNFUM
 AFGHDEHG / NMUFNFUM
 AFEDDEFA / NMUFNFUM
 AFBCDECB / NMUFNFUM
 AHEDDEHA / NMUFNFUM
 AHBCDECB / NMUFNFUM
 AHBCDGCB / NMUFNFUM
 AHBGDECF / NMUFNFUM
 ABCFFCBA / NMUFNFUM
 ABEDFCDE / NMUFNFUM
 ABHGFCGH / NMUFNFUM
 ABCDFEDC / NMUFNFUM
 ABCHFEDG / NMUFNFUM
 ABEFFEBA / NMUFNFUM
 ABHGFEGH / NMUFNFUM
 ADEFFEDA / NMUFNFUM
 ADHGFEGH / NMUFNFUM
 ADCBFEBC / NMUFNFUM
 AHDEFGED / NMUFNFUM
 AHBCFGCB / NMUFNFUM
 AHDCFGEB / NMUFNFUM
 AHBEFGCD / NMUFNFUM
 AHCBFGDE / NMUFNFUM
 AHBCFGED / NMUFNFUM
 AHCDFGDC / NMUFNFUM
 AHBEFGEB / NMUFNFUM
 ABCHHCBA / NMUFNFUM
 ABEDHCDE / NMUFNFUM
 ABEFHCDG / NMUFNFUM
 ABFGHCED / NMUFNFUM
 ABFEHCEF / NMUFNFUM
 ABGFHCDE / NMUFNFUM
 ABGDHCDG / NMUFNFUM
 ABGFHCFG / NMUFNFUM
 ABGDHCFE / NMUFNFUM
 ABCDHEDC / NMUFNFUM
 ABEHHEBA / NMUFNFUM
 ABGFHEFG / NMUFNFUM
 ABCDHGDC / NMUFNFUM
 ABCFHGDE / NMUFNFUM
 ABCDHGFE / NMUFNFUM
 ABCFHGFC / NMUFNFUM
 ABDCHGEF / NMUFNFUM
 ABDEHGED / NMUFNFUM
 ABEFHGFE / NMUFNFUM
 ABEDHGFC / NMUFNFUM
 ABGHHGBA / NMUFNFUM
 ADGFHEFG / NMUFNFUM
 ADEFHGFE / NMUFNFUM
 ADGHHGDA / NMUFNFUM
 ADEHHEDA / NMUFNFUM
 ADCBHEBC / NMUFNFUM
 ADCBHGBC / NMUFNFUM
 ADCBHEFG / NMUFNFUM
 ADBCHEGF / NMUFNFUM
 AFGHHGFA / NMUFNFUM
 AFEDHGDE / NMUFNFUM
 AFCBHGBC / NMUFNFUM
 AFEBHGDC / NMUFNFUM
 AFCDHGBE / NMUFNFUM
 AFDEHGCB / NMUFNFUM
 AFEDHGBC / NMUFNFUM
 AFDCHGCD / NMUFNFUM
 AFEBHGBE / NMUFNFUM
 ADCBBCDA / NMUFUMNF
 ADEFBCFE / NMUFUMNF
 ADEHBCFG / NMUFUMNF
 ADFEBCGH / NMUFUMNF
 ADFGBCGF / NMUFUMNF
 ADEFBCHG / NMUFUMNF
 ADEHBCHE / NMUFUMNF
 ADGHBCHG / NMUFUMNF
 ADGFBCHE / NMUFUMNF
 AFEDBCDE / NMUFUMNF
 AFCBBCFA / NMUFUMNF
 AFGHBCHG / NMUFUMNF
 AFGHBEHG / NMUFUMNF
 AFEBBEFA / NMUFUMNF
 AFCDBEDC / NMUFUMNF
 AFGHBEDC / NMUFUMNF
 AFHGBECD / NMUFUMNF
 AHEDBCDE / NMUFUMNF
 AHCBBCHA / NMUFUMNF
 AHEBBEHA / NMUFUMNF
 AHCDBEDC / NMUFUMNF
 AHCDBGDC / NMUFUMNF
 ABCDDCBA / NMUFUMNF
 ABFEDCEF / NMUFUMNF
 ABFGDCEH / NMUFUMNF
 ABGHDCFE / NMUFUMNF
 ABGFDCFG / NMUFUMNF
 ABHGDCEF / NMUFUMNF
 ABHEDCEH / NMUFUMNF
 ABHGDCGH / NMUFUMNF
 ABHEDCGF / NMUFUMNF
 AFGHDEHG / NMUFUMNF
 AFEDDEFA / NMUFUMNF
 AFBCDECB / NMUFUMNF
 AHEDDEHA / NMUFUMNF
 AHBCDECB / NMUFUMNF
 AHBCDGCB / NMUFUMNF
 AHBGDECF / NMUFUMNF
 ABCFFCBA / NMUFUMNF
 ABEDFCDE / NMUFUMNF
 ABHGFCGH / NMUFUMNF
 ABCDFEDC / NMUFUMNF
 ABCHFEDG / NMUFUMNF
 ABEFFEBA / NMUFUMNF
 ABHGFEGH / NMUFUMNF
 ADEFFEDA / NMUFUMNF
 ADHGFEGH / NMUFUMNF
 ADCBFEBC / NMUFUMNF
 AHDEFGED / NMUFUMNF
 AHBCFGCB / NMUFUMNF
 AHDCFGEB / NMUFUMNF
 AHBEFGCD / NMUFUMNF
 AHCBFGDE / NMUFUMNF
 AHBCFGED / NMUFUMNF
 AHCDFGDC / NMUFUMNF
 AHBEFGEB / NMUFUMNF
 ABCHHCBA / NMUFUMNF
 ABEDHCDE / NMUFUMNF
 ABEFHCDG / NMUFUMNF
 ABFGHCED / NMUFUMNF
 ABFEHCEF / NMUFUMNF
 ABGFHCDE / NMUFUMNF
 ABGDHCDG / NMUFUMNF
 ABGFHCFG / NMUFUMNF
 ABGDHCFE / NMUFUMNF
 ABCDHEDC / NMUFUMNF
 ABEHHEBA / NMUFUMNF
 ABGFHEFG / NMUFUMNF
 ABCDHGDC / NMUFUMNF
 ABCFHGDE / NMUFUMNF
 ABCDHGFE / NMUFUMNF
 ABCFHGFC / NMUFUMNF
 ABDCHGEF / NMUFUMNF
 ABDEHGED / NMUFUMNF
 ABEFHGFE / NMUFUMNF
 ABEDHGFC / NMUFUMNF
 ABGHHGBA / NMUFUMNF
 ADGFHEFG / NMUFUMNF
 ADEFHGFE / NMUFUMNF
 ADGHHGDA / NMUFUMNF
 ADEHHEDA / NMUFUMNF
 ADCBHEBC / NMUFUMNF
 ADCBHGBC / NMUFUMNF
 ADCBHEFG / NMUFUMNF
 ADBCHEGF / NMUFUMNF
 AFGHHGFA / NMUFUMNF
 AFEDHGDE / NMUFUMNF
 AFCBHGBC / NMUFUMNF
 AFEBHGDC / NMUFUMNF
 AFCDHGBE / NMUFUMNF
 AFDEHGCB / NMUFUMNF
 AFEDHGBC / NMUFUMNF
 AFDCHGCD / NMUFUMNF
 AFEBHGBE / NMUFUMNF
 ADCBBCDA / NMUFUFNM
 ADEFBCFE / NMUFUFNM
 ADEHBCFG / NMUFUFNM
 ADFEBCGH / NMUFUFNM
 ADFGBCGF / NMUFUFNM
 ADEFBCHG / NMUFUFNM
 ADEHBCHE / NMUFUFNM
 ADGHBCHG / NMUFUFNM
 ADGFBCHE / NMUFUFNM
 AFEDBCDE / NMUFUFNM
 AFCBBCFA / NMUFUFNM
 AFGHBCHG / NMUFUFNM
 AFGHBEHG / NMUFUFNM
 AFEBBEFA / NMUFUFNM
 AFCDBEDC / NMUFUFNM
 AFGHBEDC / NMUFUFNM
 AFHGBECD / NMUFUFNM
 AHEDBCDE / NMUFUFNM
 AHCBBCHA / NMUFUFNM
 AHEBBEHA / NMUFUFNM
 AHCDBEDC / NMUFUFNM
 AHCDBGDC / NMUFUFNM
 ABCDDCBA / NMUFUFNM
 ABFEDCEF / NMUFUFNM
 ABFGDCEH / NMUFUFNM
 ABGHDCFE / NMUFUFNM
 ABGFDCFG / NMUFUFNM
 ABHGDCEF / NMUFUFNM
 ABHEDCEH / NMUFUFNM
 ABHGDCGH / NMUFUFNM
 ABHEDCGF / NMUFUFNM
 AFGHDEHG / NMUFUFNM
 AFEDDEFA / NMUFUFNM
 AFBCDECB / NMUFUFNM
 AHEDDEHA / NMUFUFNM
 AHBCDECB / NMUFUFNM
 AHBCDGCB / NMUFUFNM
 AHBGDECF / NMUFUFNM
 ABCFFCBA / NMUFUFNM
 ABEDFCDE / NMUFUFNM
 ABHGFCGH / NMUFUFNM
 ABCDFEDC / NMUFUFNM
 ABCHFEDG / NMUFUFNM
 ABEFFEBA / NMUFUFNM
 ABHGFEGH / NMUFUFNM
 ADEFFEDA / NMUFUFNM
 ADHGFEGH / NMUFUFNM
 ADCBFEBC / NMUFUFNM
 AHDEFGED / NMUFUFNM
 AHBCFGCB / NMUFUFNM
 AHDCFGEB / NMUFUFNM
 AHBEFGCD / NMUFUFNM
 AHCBFGDE / NMUFUFNM
 AHBCFGED / NMUFUFNM
 AHCDFGDC / NMUFUFNM
 AHBEFGEB / NMUFUFNM
 ABCHHCBA / NMUFUFNM
 ABEDHCDE / NMUFUFNM
 ABEFHCDG / NMUFUFNM
 ABFGHCED / NMUFUFNM
 ABFEHCEF / NMUFUFNM
 ABGFHCDE / NMUFUFNM
 ABGDHCDG / NMUFUFNM
 ABGFHCFG / NMUFUFNM
 ABGDHCFE / NMUFUFNM
 ABCDHEDC / NMUFUFNM
 ABEHHEBA / NMUFUFNM
 ABGFHEFG / NMUFUFNM
 ABCDHGDC / NMUFUFNM
 ABCFHGDE / NMUFUFNM
 ABCDHGFE / NMUFUFNM
 ABCFHGFC / NMUFUFNM
 ABDCHGEF / NMUFUFNM
 ABDEHGED / NMUFUFNM
 ABEFHGFE / NMUFUFNM
 ABEDHGFC / NMUFUFNM
 ABGHHGBA / NMUFUFNM
 ADGFHEFG / NMUFUFNM
 ADEFHGFE / NMUFUFNM
 ADGHHGDA / NMUFUFNM
 ADEHHEDA / NMUFUFNM
 ADCBHEBC / NMUFUFNM
 ADCBHGBC / NMUFUFNM
 ADCBHEFG / NMUFUFNM
 ADBCHEGF / NMUFUFNM
 AFGHHGFA / NMUFUFNM
 AFEDHGDE / NMUFUFNM
 AFCBHGBC / NMUFUFNM
 AFEBHGDC / NMUFUFNM
 AFCDHGBE / NMUFUFNM
 AFDEHGCB / NMUFUFNM
 AFEDHGBC / NMUFUFNM
 AFDCHGCD / NMUFUFNM
 AFEBHGBE / NMUFUFNM
 ADCBBCDA / NFNMUMUF
 ADEFBCFE / NFNMUMUF
 ADEHBCFG / NFNMUMUF
 ADFEBCGH / NFNMUMUF
 ADFGBCGF / NFNMUMUF
 ADEFBCHG / NFNMUMUF
 ADEHBCHE / NFNMUMUF
 ADGHBCHG / NFNMUMUF
 ADGFBCHE / NFNMUMUF
 AFEDBCDE / NFNMUMUF
 AFCBBCFA / NFNMUMUF
 AFGHBCHG / NFNMUMUF
 AFGHBEHG / NFNMUMUF
 AFEBBEFA / NFNMUMUF
 AFCDBEDC / NFNMUMUF
 AFGHBEDC / NFNMUMUF
 AFHGBECD / NFNMUMUF
 AHEDBCDE / NFNMUMUF
 AHCBBCHA / NFNMUMUF
 AHEBBEHA / NFNMUMUF
 AHCDBEDC / NFNMUMUF
 AHCDBGDC / NFNMUMUF
 ABCDDCBA / NFNMUMUF
 ABFEDCEF / NFNMUMUF
 ABFGDCEH / NFNMUMUF
 ABGHDCFE / NFNMUMUF
 ABGFDCFG / NFNMUMUF
 ABHGDCEF / NFNMUMUF
 ABHEDCEH / NFNMUMUF
 ABHGDCGH / NFNMUMUF
 ABHEDCGF / NFNMUMUF
 AFGHDEHG / NFNMUMUF
 AFEDDEFA / NFNMUMUF
 AFBCDECB / NFNMUMUF
 AHEDDEHA / NFNMUMUF
 AHBCDECB / NFNMUMUF
 AHBCDGCB / NFNMUMUF
 AHBGDECF / NFNMUMUF
 ABCFFCBA / NFNMUMUF
 ABEDFCDE / NFNMUMUF
 ABHGFCGH / NFNMUMUF
 ABCDFEDC / NFNMUMUF
 ABCHFEDG / NFNMUMUF
 ABEFFEBA / NFNMUMUF
 ABHGFEGH / NFNMUMUF
 ADEFFEDA / NFNMUMUF
 ADHGFEGH / NFNMUMUF
 ADCBFEBC / NFNMUMUF
 AHDEFGED / NFNMUMUF
 AHBCFGCB / NFNMUMUF
 AHDCFGEB / NFNMUMUF
 AHBEFGCD / NFNMUMUF
 AHCBFGDE / NFNMUMUF
 AHBCFGED / NFNMUMUF
 AHCDFGDC / NFNMUMUF
 AHBEFGEB / NFNMUMUF
 ABCHHCBA / NFNMUMUF
 ABEDHCDE / NFNMUMUF
 ABEFHCDG / NFNMUMUF
 ABFGHCED / NFNMUMUF
 ABFEHCEF / NFNMUMUF
 ABGFHCDE / NFNMUMUF
 ABGDHCDG / NFNMUMUF
 ABGFHCFG / NFNMUMUF
 ABGDHCFE / NFNMUMUF
 ABCDHEDC / NFNMUMUF
 ABEHHEBA / NFNMUMUF
 ABGFHEFG / NFNMUMUF
 ABCDHGDC / NFNMUMUF
 ABCFHGDE / NFNMUMUF
 ABCDHGFE / NFNMUMUF
 ABCFHGFC / NFNMUMUF
 ABDCHGEF / NFNMUMUF
 ABDEHGED / NFNMUMUF
 ABEFHGFE / NFNMUMUF
 ABEDHGFC / NFNMUMUF
 ABGHHGBA / NFNMUMUF
 ADGFHEFG / NFNMUMUF
 ADEFHGFE / NFNMUMUF
 ADGHHGDA / NFNMUMUF
 ADEHHEDA / NFNMUMUF
 ADCBHEBC / NFNMUMUF
 ADCBHGBC / NFNMUMUF
 ADCBHEFG / NFNMUMUF
 ADBCHEGF / NFNMUMUF
 AFGHHGFA / NFNMUMUF
 AFEDHGDE / NFNMUMUF
 AFCBHGBC / NFNMUMUF
 AFEBHGDC / NFNMUMUF
 AFCDHGBE / NFNMUMUF
 AFDEHGCB / NFNMUMUF
 AFEDHGBC / NFNMUMUF
 AFDCHGCD / NFNMUMUF
 AFEBHGBE / NFNMUMUF
 ADCBBCDA / NFNMUFUM
 ADEFBCFE / NFNMUFUM
 ADEHBCFG / NFNMUFUM
 ADFEBCGH / NFNMUFUM
 ADFGBCGF / NFNMUFUM
 ADEFBCHG / NFNMUFUM
 ADEHBCHE / NFNMUFUM
 ADGHBCHG / NFNMUFUM
 ADGFBCHE / NFNMUFUM
 AFEDBCDE / NFNMUFUM
 AFCBBCFA / NFNMUFUM
 AFGHBCHG / NFNMUFUM
 AFGHBEHG / NFNMUFUM
 AFEBBEFA / NFNMUFUM
 AFCDBEDC / NFNMUFUM
 AFGHBEDC / NFNMUFUM
 AFHGBECD / NFNMUFUM
 AHEDBCDE / NFNMUFUM
 AHCBBCHA / NFNMUFUM
 AHEBBEHA / NFNMUFUM
 AHCDBEDC / NFNMUFUM
 AHCDBGDC / NFNMUFUM
 ABCDDCBA / NFNMUFUM
 ABFEDCEF / NFNMUFUM
 ABFGDCEH / NFNMUFUM
 ABGHDCFE / NFNMUFUM
 ABGFDCFG / NFNMUFUM
 ABHGDCEF / NFNMUFUM
 ABHEDCEH / NFNMUFUM
 ABHGDCGH / NFNMUFUM
 ABHEDCGF / NFNMUFUM
 AFGHDEHG / NFNMUFUM
 AFEDDEFA / NFNMUFUM
 AFBCDECB / NFNMUFUM
 AHEDDEHA / NFNMUFUM
 AHBCDECB / NFNMUFUM
 AHBCDGCB / NFNMUFUM
 AHBGDECF / NFNMUFUM
 ABCFFCBA / NFNMUFUM
 ABEDFCDE / NFNMUFUM
 ABHGFCGH / NFNMUFUM
 ABCDFEDC / NFNMUFUM
 ABCHFEDG / NFNMUFUM
 ABEFFEBA / NFNMUFUM
 ABHGFEGH / NFNMUFUM
 ADEFFEDA / NFNMUFUM
 ADHGFEGH / NFNMUFUM
 ADCBFEBC / NFNMUFUM
 AHDEFGED / NFNMUFUM
 AHBCFGCB / NFNMUFUM
 AHDCFGEB / NFNMUFUM
 AHBEFGCD / NFNMUFUM
 AHCBFGDE / NFNMUFUM
 AHBCFGED / NFNMUFUM
 AHCDFGDC / NFNMUFUM
 AHBEFGEB / NFNMUFUM
 ABCHHCBA / NFNMUFUM
 ABEDHCDE / NFNMUFUM
 ABEFHCDG / NFNMUFUM
 ABFGHCED / NFNMUFUM
 ABFEHCEF / NFNMUFUM
 ABGFHCDE / NFNMUFUM
 ABGDHCDG / NFNMUFUM
 ABGFHCFG / NFNMUFUM
 ABGDHCFE / NFNMUFUM
 ABCDHEDC / NFNMUFUM
 ABEHHEBA / NFNMUFUM
 ABGFHEFG / NFNMUFUM
 ABCDHGDC / NFNMUFUM
 ABCFHGDE / NFNMUFUM
 ABCDHGFE / NFNMUFUM
 ABCFHGFC / NFNMUFUM
 ABDCHGEF / NFNMUFUM
 ABDEHGED / NFNMUFUM
 ABEFHGFE / NFNMUFUM
 ABEDHGFC / NFNMUFUM
 ABGHHGBA / NFNMUFUM
 ADGFHEFG / NFNMUFUM
 ADEFHGFE / NFNMUFUM
 ADGHHGDA / NFNMUFUM
 ADEHHEDA / NFNMUFUM
 ADCBHEBC / NFNMUFUM
 ADCBHGBC / NFNMUFUM
 ADCBHEFG / NFNMUFUM
 ADBCHEGF / NFNMUFUM
 AFGHHGFA / NFNMUFUM
 AFEDHGDE / NFNMUFUM
 AFCBHGBC / NFNMUFUM
 AFEBHGDC / NFNMUFUM
 AFCDHGBE / NFNMUFUM
 AFDEHGCB / NFNMUFUM
 AFEDHGBC / NFNMUFUM
 AFDCHGCD / NFNMUFUM
 AFEBHGBE / NFNMUFUM
 ADCBBCDA / NFNFUMUM
 ADEFBCFE / NFNFUMUM
 ADEHBCFG / NFNFUMUM
 ADFEBCGH / NFNFUMUM
 ADFGBCGF / NFNFUMUM
 ADEFBCHG / NFNFUMUM
 ADEHBCHE / NFNFUMUM
 ADGHBCHG / NFNFUMUM
 ADGFBCHE / NFNFUMUM
 AFEDBCDE / NFNFUMUM
 AFCBBCFA / NFNFUMUM
 AFGHBCHG / NFNFUMUM
 AFGHBEHG / NFNFUMUM
 AFEBBEFA / NFNFUMUM
 AFCDBEDC / NFNFUMUM
 AFGHBEDC / NFNFUMUM
 AFHGBECD / NFNFUMUM
 AHEDBCDE / NFNFUMUM
 AHCBBCHA / NFNFUMUM
 AHEBBEHA / NFNFUMUM
 AHCDBEDC / NFNFUMUM
 AHCDBGDC / NFNFUMUM
 ABCDDCBA / NFNFUMUM
 ABFEDCEF / NFNFUMUM
 ABFGDCEH / NFNFUMUM
 ABGHDCFE / NFNFUMUM
 ABGFDCFG / NFNFUMUM
 ABHGDCEF / NFNFUMUM
 ABHEDCEH / NFNFUMUM
 ABHGDCGH / NFNFUMUM
 ABHEDCGF / NFNFUMUM
 AFGHDEHG / NFNFUMUM
 AFEDDEFA / NFNFUMUM
 AFBCDECB / NFNFUMUM
 AHEDDEHA / NFNFUMUM
 AHBCDECB / NFNFUMUM
 AHBCDGCB / NFNFUMUM
 AHBGDECF / NFNFUMUM
 ABCFFCBA / NFNFUMUM
 ABEDFCDE / NFNFUMUM
 ABHGFCGH / NFNFUMUM
 ABCDFEDC / NFNFUMUM
 ABCHFEDG / NFNFUMUM
 ABEFFEBA / NFNFUMUM
 ABHGFEGH / NFNFUMUM
 ADEFFEDA / NFNFUMUM
 ADHGFEGH / NFNFUMUM
 ADCBFEBC / NFNFUMUM
 AHDEFGED / NFNFUMUM
 AHBCFGCB / NFNFUMUM
 AHDCFGEB / NFNFUMUM
 AHBEFGCD / NFNFUMUM
 AHCBFGDE / NFNFUMUM
 AHBCFGED / NFNFUMUM
 AHCDFGDC / NFNFUMUM
 AHBEFGEB / NFNFUMUM
 ABCHHCBA / NFNFUMUM
 ABEDHCDE / NFNFUMUM
 ABEFHCDG / NFNFUMUM
 ABFGHCED / NFNFUMUM
 ABFEHCEF / NFNFUMUM
 ABGFHCDE / NFNFUMUM
 ABGDHCDG / NFNFUMUM
 ABGFHCFG / NFNFUMUM
 ABGDHCFE / NFNFUMUM
 ABCDHEDC / NFNFUMUM
 ABEHHEBA / NFNFUMUM
 ABGFHEFG / NFNFUMUM
 ABCDHGDC / NFNFUMUM
 ABCFHGDE / NFNFUMUM
 ABCDHGFE / NFNFUMUM
 ABCFHGFC / NFNFUMUM
 ABDCHGEF / NFNFUMUM
 ABDEHGED / NFNFUMUM
 ABEFHGFE / NFNFUMUM
 ABEDHGFC / NFNFUMUM
 ABGHHGBA / NFNFUMUM
 ADGFHEFG / NFNFUMUM
 ADEFHGFE / NFNFUMUM
 ADGHHGDA / NFNFUMUM
 ADEHHEDA / NFNFUMUM
 ADCBHEBC / NFNFUMUM
 ADCBHGBC / NFNFUMUM
 ADCBHEFG / NFNFUMUM
 ADBCHEGF / NFNFUMUM
 AFGHHGFA / NFNFUMUM
 AFEDHGDE / NFNFUMUM
 AFCBHGBC / NFNFUMUM
 AFEBHGDC / NFNFUMUM
 AFCDHGBE / NFNFUMUM
 AFDEHGCB / NFNFUMUM
 AFEDHGBC / NFNFUMUM
 AFDCHGCD / NFNFUMUM
 AFEBHGBE / NFNFUMUM
 ADCBBCDA / NFUMNMUF
 ADEFBCFE / NFUMNMUF
 ADEHBCFG / NFUMNMUF
 ADFEBCGH / NFUMNMUF
 ADFGBCGF / NFUMNMUF
 ADEFBCHG / NFUMNMUF
 ADEHBCHE / NFUMNMUF
 ADGHBCHG / NFUMNMUF
 ADGFBCHE / NFUMNMUF
 AFEDBCDE / NFUMNMUF
 AFCBBCFA / NFUMNMUF
 AFGHBCHG / NFUMNMUF
 AFGHBEHG / NFUMNMUF
 AFEBBEFA / NFUMNMUF
 AFCDBEDC / NFUMNMUF
 AFGHBEDC / NFUMNMUF
 AFHGBECD / NFUMNMUF
 AHEDBCDE / NFUMNMUF
 AHCBBCHA / NFUMNMUF
 AHEBBEHA / NFUMNMUF
 AHCDBEDC / NFUMNMUF
 AHCDBGDC / NFUMNMUF
 ABCDDCBA / NFUMNMUF
 ABFEDCEF / NFUMNMUF
 ABFGDCEH / NFUMNMUF
 ABGHDCFE / NFUMNMUF
 ABGFDCFG / NFUMNMUF
 ABHGDCEF / NFUMNMUF
 ABHEDCEH / NFUMNMUF
 ABHGDCGH / NFUMNMUF
 ABHEDCGF / NFUMNMUF
 AFGHDEHG / NFUMNMUF
 AFEDDEFA / NFUMNMUF
 AFBCDECB / NFUMNMUF
 AHEDDEHA / NFUMNMUF
 AHBCDECB / NFUMNMUF
 AHBCDGCB / NFUMNMUF
 AHBGDECF / NFUMNMUF
 ABCFFCBA / NFUMNMUF
 ABEDFCDE / NFUMNMUF
 ABHGFCGH / NFUMNMUF
 ABCDFEDC / NFUMNMUF
 ABCHFEDG / NFUMNMUF
 ABEFFEBA / NFUMNMUF
 ABHGFEGH / NFUMNMUF
 ADEFFEDA / NFUMNMUF
 ADHGFEGH / NFUMNMUF
 ADCBFEBC / NFUMNMUF
 AHDEFGED / NFUMNMUF
 AHBCFGCB / NFUMNMUF
 AHDCFGEB / NFUMNMUF
 AHBEFGCD / NFUMNMUF
 AHCBFGDE / NFUMNMUF
 AHBCFGED / NFUMNMUF
 AHCDFGDC / NFUMNMUF
 AHBEFGEB / NFUMNMUF
 ABCHHCBA / NFUMNMUF
 ABEDHCDE / NFUMNMUF
 ABEFHCDG / NFUMNMUF
 ABFGHCED / NFUMNMUF
 ABFEHCEF / NFUMNMUF
 ABGFHCDE / NFUMNMUF
 ABGDHCDG / NFUMNMUF
 ABGFHCFG / NFUMNMUF
 ABGDHCFE / NFUMNMUF
 ABCDHEDC / NFUMNMUF
 ABEHHEBA / NFUMNMUF
 ABGFHEFG / NFUMNMUF
 ABCDHGDC / NFUMNMUF
 ABCFHGDE / NFUMNMUF
 ABCDHGFE / NFUMNMUF
 ABCFHGFC / NFUMNMUF
 ABDCHGEF / NFUMNMUF
 ABDEHGED / NFUMNMUF
 ABEFHGFE / NFUMNMUF
 ABEDHGFC / NFUMNMUF
 ABGHHGBA / NFUMNMUF
 ADGFHEFG / NFUMNMUF
 ADEFHGFE / NFUMNMUF
 ADGHHGDA / NFUMNMUF
 ADEHHEDA / NFUMNMUF
 ADCBHEBC / NFUMNMUF
 ADCBHGBC / NFUMNMUF
 ADCBHEFG / NFUMNMUF
 ADBCHEGF / NFUMNMUF
 AFGHHGFA / NFUMNMUF
 AFEDHGDE / NFUMNMUF
 AFCBHGBC / NFUMNMUF
 AFEBHGDC / NFUMNMUF
 AFCDHGBE / NFUMNMUF
 AFDEHGCB / NFUMNMUF
 AFEDHGBC / NFUMNMUF
 AFDCHGCD / NFUMNMUF
 AFEBHGBE / NFUMNMUF
 ADCBBCDA / NFUMNFUM
 ADEFBCFE / NFUMNFUM
 ADEHBCFG / NFUMNFUM
 ADFEBCGH / NFUMNFUM
 ADFGBCGF / NFUMNFUM
 ADEFBCHG / NFUMNFUM
 ADEHBCHE / NFUMNFUM
 ADGHBCHG / NFUMNFUM
 ADGFBCHE / NFUMNFUM
 AFEDBCDE / NFUMNFUM
 AFCBBCFA / NFUMNFUM
 AFGHBCHG / NFUMNFUM
 AFGHBEHG / NFUMNFUM
 AFEBBEFA / NFUMNFUM
 AFCDBEDC / NFUMNFUM
 AFGHBEDC / NFUMNFUM
 AFHGBECD / NFUMNFUM
 AHEDBCDE / NFUMNFUM
 AHCBBCHA / NFUMNFUM
 AHEBBEHA / NFUMNFUM
 AHCDBEDC / NFUMNFUM
 AHCDBGDC / NFUMNFUM
 ABCDDCBA / NFUMNFUM
 ABFEDCEF / NFUMNFUM
 ABFGDCEH / NFUMNFUM
 ABGHDCFE / NFUMNFUM
 ABGFDCFG / NFUMNFUM
 ABHGDCEF / NFUMNFUM
 ABHEDCEH / NFUMNFUM
 ABHGDCGH / NFUMNFUM
 ABHEDCGF / NFUMNFUM
 AFGHDEHG / NFUMNFUM
 AFEDDEFA / NFUMNFUM
 AFBCDECB / NFUMNFUM
 AHEDDEHA / NFUMNFUM
 AHBCDECB / NFUMNFUM
 AHBCDGCB / NFUMNFUM
 AHBGDECF / NFUMNFUM
 ABCFFCBA / NFUMNFUM
 ABEDFCDE / NFUMNFUM
 ABHGFCGH / NFUMNFUM
 ABCDFEDC / NFUMNFUM
 ABCHFEDG / NFUMNFUM
 ABEFFEBA / NFUMNFUM
 ABHGFEGH / NFUMNFUM
 ADEFFEDA / NFUMNFUM
 ADHGFEGH / NFUMNFUM
 ADCBFEBC / NFUMNFUM
 AHDEFGED / NFUMNFUM
 AHBCFGCB / NFUMNFUM
 AHDCFGEB / NFUMNFUM
 AHBEFGCD / NFUMNFUM
 AHCBFGDE / NFUMNFUM
 AHBCFGED / NFUMNFUM
 AHCDFGDC / NFUMNFUM
 AHBEFGEB / NFUMNFUM
 ABCHHCBA / NFUMNFUM
 ABEDHCDE / NFUMNFUM
 ABEFHCDG / NFUMNFUM
 ABFGHCED / NFUMNFUM
 ABFEHCEF / NFUMNFUM
 ABGFHCDE / NFUMNFUM
 ABGDHCDG / NFUMNFUM
 ABGFHCFG / NFUMNFUM
 ABGDHCFE / NFUMNFUM
 ABCDHEDC / NFUMNFUM
 ABEHHEBA / NFUMNFUM
 ABGFHEFG / NFUMNFUM
 ABCDHGDC / NFUMNFUM
 ABCFHGDE / NFUMNFUM
 ABCDHGFE / NFUMNFUM
 ABCFHGFC / NFUMNFUM
 ABDCHGEF / NFUMNFUM
 ABDEHGED / NFUMNFUM
 ABEFHGFE / NFUMNFUM
 ABEDHGFC / NFUMNFUM
 ABGHHGBA / NFUMNFUM
 ADGFHEFG / NFUMNFUM
 ADEFHGFE / NFUMNFUM
 ADGHHGDA / NFUMNFUM
 ADEHHEDA / NFUMNFUM
 ADCBHEBC / NFUMNFUM
 ADCBHGBC / NFUMNFUM
 ADCBHEFG / NFUMNFUM
 ADBCHEGF / NFUMNFUM
 AFGHHGFA / NFUMNFUM
 AFEDHGDE / NFUMNFUM
 AFCBHGBC / NFUMNFUM
 AFEBHGDC / NFUMNFUM
 AFCDHGBE / NFUMNFUM
 AFDEHGCB / NFUMNFUM
 AFEDHGBC / NFUMNFUM
 AFDCHGCD / NFUMNFUM
 AFEBHGBE / NFUMNFUM
 ADCBBCDA / NFUMUMNF
 ADEFBCFE / NFUMUMNF
 ADEHBCFG / NFUMUMNF
 ADFEBCGH / NFUMUMNF
 ADFGBCGF / NFUMUMNF
 ADEFBCHG / NFUMUMNF
 ADEHBCHE / NFUMUMNF
 ADGHBCHG / NFUMUMNF
 ADGFBCHE / NFUMUMNF
 AFEDBCDE / NFUMUMNF
 AFCBBCFA / NFUMUMNF
 AFGHBCHG / NFUMUMNF
 AFGHBEHG / NFUMUMNF
 AFEBBEFA / NFUMUMNF
 AFCDBEDC / NFUMUMNF
 AFGHBEDC / NFUMUMNF
 AFHGBECD / NFUMUMNF
 AHEDBCDE / NFUMUMNF
 AHCBBCHA / NFUMUMNF
 AHEBBEHA / NFUMUMNF
 AHCDBEDC / NFUMUMNF
 AHCDBGDC / NFUMUMNF
 ABCDDCBA / NFUMUMNF
 ABFEDCEF / NFUMUMNF
 ABFGDCEH / NFUMUMNF
 ABGHDCFE / NFUMUMNF
 ABGFDCFG / NFUMUMNF
 ABHGDCEF / NFUMUMNF
 ABHEDCEH / NFUMUMNF
 ABHGDCGH / NFUMUMNF
 ABHEDCGF / NFUMUMNF
 AFGHDEHG / NFUMUMNF
 AFEDDEFA / NFUMUMNF
 AFBCDECB / NFUMUMNF
 AHEDDEHA / NFUMUMNF
 AHBCDECB / NFUMUMNF
 AHBCDGCB / NFUMUMNF
 AHBGDECF / NFUMUMNF
 ABCFFCBA / NFUMUMNF
 ABEDFCDE / NFUMUMNF
 ABHGFCGH / NFUMUMNF
 ABCDFEDC / NFUMUMNF
 ABCHFEDG / NFUMUMNF
 ABEFFEBA / NFUMUMNF
 ABHGFEGH / NFUMUMNF
 ADEFFEDA / NFUMUMNF
 ADHGFEGH / NFUMUMNF
 ADCBFEBC / NFUMUMNF
 AHDEFGED / NFUMUMNF
 AHBCFGCB / NFUMUMNF
 AHDCFGEB / NFUMUMNF
 AHBEFGCD / NFUMUMNF
 AHCBFGDE / NFUMUMNF
 AHBCFGED / NFUMUMNF
 AHCDFGDC / NFUMUMNF
 AHBEFGEB / NFUMUMNF
 ABCHHCBA / NFUMUMNF
 ABEDHCDE / NFUMUMNF
 ABEFHCDG / NFUMUMNF
 ABFGHCED / NFUMUMNF
 ABFEHCEF / NFUMUMNF
 ABGFHCDE / NFUMUMNF
 ABGDHCDG / NFUMUMNF
 ABGFHCFG / NFUMUMNF
 ABGDHCFE / NFUMUMNF
 ABCDHEDC / NFUMUMNF
 ABEHHEBA / NFUMUMNF
 ABGFHEFG / NFUMUMNF
 ABCDHGDC / NFUMUMNF
 ABCFHGDE / NFUMUMNF
 ABCDHGFE / NFUMUMNF
 ABCFHGFC / NFUMUMNF
 ABDCHGEF / NFUMUMNF
 ABDEHGED / NFUMUMNF
 ABEFHGFE / NFUMUMNF
 ABEDHGFC / NFUMUMNF
 ABGHHGBA / NFUMUMNF
 ADGFHEFG / NFUMUMNF
 ADEFHGFE / NFUMUMNF
 ADGHHGDA / NFUMUMNF
 ADEHHEDA / NFUMUMNF
 ADCBHEBC / NFUMUMNF
 ADCBHGBC / NFUMUMNF
 ADCBHEFG / NFUMUMNF
 ADBCHEGF / NFUMUMNF
 AFGHHGFA / NFUMUMNF
 AFEDHGDE / NFUMUMNF
 AFCBHGBC / NFUMUMNF
 AFEBHGDC / NFUMUMNF
 AFCDHGBE / NFUMUMNF
 AFDEHGCB / NFUMUMNF
 AFEDHGBC / NFUMUMNF
 AFDCHGCD / NFUMUMNF
 AFEBHGBE / NFUMUMNF
 ADCBBCDA / NFUMUFNM
 ADEFBCFE / NFUMUFNM
 ADEHBCFG / NFUMUFNM
 ADFEBCGH / NFUMUFNM
 ADFGBCGF / NFUMUFNM
 ADEFBCHG / NFUMUFNM
 ADEHBCHE / NFUMUFNM
 ADGHBCHG / NFUMUFNM
 ADGFBCHE / NFUMUFNM
 AFEDBCDE / NFUMUFNM
 AFCBBCFA / NFUMUFNM
 AFGHBCHG / NFUMUFNM
 AFGHBEHG / NFUMUFNM
 AFEBBEFA / NFUMUFNM
 AFCDBEDC / NFUMUFNM
 AFGHBEDC / NFUMUFNM
 AFHGBECD / NFUMUFNM
 AHEDBCDE / NFUMUFNM
 AHCBBCHA / NFUMUFNM
 AHEBBEHA / NFUMUFNM
 AHCDBEDC / NFUMUFNM
 AHCDBGDC / NFUMUFNM
 ABCDDCBA / NFUMUFNM
 ABFEDCEF / NFUMUFNM
 ABFGDCEH / NFUMUFNM
 ABGHDCFE / NFUMUFNM
 ABGFDCFG / NFUMUFNM
 ABHGDCEF / NFUMUFNM
 ABHEDCEH / NFUMUFNM
 ABHGDCGH / NFUMUFNM
 ABHEDCGF / NFUMUFNM
 AFGHDEHG / NFUMUFNM
 AFEDDEFA / NFUMUFNM
 AFBCDECB / NFUMUFNM
 AHEDDEHA / NFUMUFNM
 AHBCDECB / NFUMUFNM
 AHBCDGCB / NFUMUFNM
 AHBGDECF / NFUMUFNM
 ABCFFCBA / NFUMUFNM
 ABEDFCDE / NFUMUFNM
 ABHGFCGH / NFUMUFNM
 ABCDFEDC / NFUMUFNM
 ABCHFEDG / NFUMUFNM
 ABEFFEBA / NFUMUFNM
 ABHGFEGH / NFUMUFNM
 ADEFFEDA / NFUMUFNM
 ADHGFEGH / NFUMUFNM
 ADCBFEBC / NFUMUFNM
 AHDEFGED / NFUMUFNM
 AHBCFGCB / NFUMUFNM
 AHDCFGEB / NFUMUFNM
 AHBEFGCD / NFUMUFNM
 AHCBFGDE / NFUMUFNM
 AHBCFGED / NFUMUFNM
 AHCDFGDC / NFUMUFNM
 AHBEFGEB / NFUMUFNM
 ABCHHCBA / NFUMUFNM
 ABEDHCDE / NFUMUFNM
 ABEFHCDG / NFUMUFNM
 ABFGHCED / NFUMUFNM
 ABFEHCEF / NFUMUFNM
 ABGFHCDE / NFUMUFNM
 ABGDHCDG / NFUMUFNM
 ABGFHCFG / NFUMUFNM
 ABGDHCFE / NFUMUFNM
 ABCDHEDC / NFUMUFNM
 ABEHHEBA / NFUMUFNM
 ABGFHEFG / NFUMUFNM
 ABCDHGDC / NFUMUFNM
 ABCFHGDE / NFUMUFNM
 ABCDHGFE / NFUMUFNM
 ABCFHGFC / NFUMUFNM
 ABDCHGEF / NFUMUFNM
 ABDEHGED / NFUMUFNM
 ABEFHGFE / NFUMUFNM
 ABEDHGFC / NFUMUFNM
 ABGHHGBA / NFUMUFNM
 ADGFHEFG / NFUMUFNM
 ADEFHGFE / NFUMUFNM
 ADGHHGDA / NFUMUFNM
 ADEHHEDA / NFUMUFNM
 ADCBHEBC / NFUMUFNM
 ADCBHGBC / NFUMUFNM
 ADCBHEFG / NFUMUFNM
 ADBCHEGF / NFUMUFNM
 AFGHHGFA / NFUMUFNM
 AFEDHGDE / NFUMUFNM
 AFCBHGBC / NFUMUFNM
 AFEBHGDC / NFUMUFNM
 AFCDHGBE / NFUMUFNM
 AFDEHGCB / NFUMUFNM
 AFEDHGBC / NFUMUFNM
 AFDCHGCD / NFUMUFNM
 AFEBHGBE / NFUMUFNM
 ADCBBCDA / NFUFNMUM
 ADEFBCFE / NFUFNMUM
 ADEHBCFG / NFUFNMUM
 ADFEBCGH / NFUFNMUM
 ADFGBCGF / NFUFNMUM
 ADEFBCHG / NFUFNMUM
 ADEHBCHE / NFUFNMUM
 ADGHBCHG / NFUFNMUM
 ADGFBCHE / NFUFNMUM
 AFEDBCDE / NFUFNMUM
 AFCBBCFA / NFUFNMUM
 AFGHBCHG / NFUFNMUM
 AFGHBEHG / NFUFNMUM
 AFEBBEFA / NFUFNMUM
 AFCDBEDC / NFUFNMUM
 AFGHBEDC / NFUFNMUM
 AFHGBECD / NFUFNMUM
 AHEDBCDE / NFUFNMUM
 AHCBBCHA / NFUFNMUM
 AHEBBEHA / NFUFNMUM
 AHCDBEDC / NFUFNMUM
 AHCDBGDC / NFUFNMUM
 ABCDDCBA / NFUFNMUM
 ABFEDCEF / NFUFNMUM
 ABFGDCEH / NFUFNMUM
 ABGHDCFE / NFUFNMUM
 ABGFDCFG / NFUFNMUM
 ABHGDCEF / NFUFNMUM
 ABHEDCEH / NFUFNMUM
 ABHGDCGH / NFUFNMUM
 ABHEDCGF / NFUFNMUM
 AFGHDEHG / NFUFNMUM
 AFEDDEFA / NFUFNMUM
 AFBCDECB / NFUFNMUM
 AHEDDEHA / NFUFNMUM
 AHBCDECB / NFUFNMUM
 AHBCDGCB / NFUFNMUM
 AHBGDECF / NFUFNMUM
 ABCFFCBA / NFUFNMUM
 ABEDFCDE / NFUFNMUM
 ABHGFCGH / NFUFNMUM
 ABCDFEDC / NFUFNMUM
 ABCHFEDG / NFUFNMUM
 ABEFFEBA / NFUFNMUM
 ABHGFEGH / NFUFNMUM
 ADEFFEDA / NFUFNMUM
 ADHGFEGH / NFUFNMUM
 ADCBFEBC / NFUFNMUM
 AHDEFGED / NFUFNMUM
 AHBCFGCB / NFUFNMUM
 AHDCFGEB / NFUFNMUM
 AHBEFGCD / NFUFNMUM
 AHCBFGDE / NFUFNMUM
 AHBCFGED / NFUFNMUM
 AHCDFGDC / NFUFNMUM
 AHBEFGEB / NFUFNMUM
 ABCHHCBA / NFUFNMUM
 ABEDHCDE / NFUFNMUM
 ABEFHCDG / NFUFNMUM
 ABFGHCED / NFUFNMUM
 ABFEHCEF / NFUFNMUM
 ABGFHCDE / NFUFNMUM
 ABGDHCDG / NFUFNMUM
 ABGFHCFG / NFUFNMUM
 ABGDHCFE / NFUFNMUM
 ABCDHEDC / NFUFNMUM
 ABEHHEBA / NFUFNMUM
 ABGFHEFG / NFUFNMUM
 ABCDHGDC / NFUFNMUM
 ABCFHGDE / NFUFNMUM
 ABCDHGFE / NFUFNMUM
 ABCFHGFC / NFUFNMUM
 ABDCHGEF / NFUFNMUM
 ABDEHGED / NFUFNMUM
 ABEFHGFE / NFUFNMUM
 ABEDHGFC / NFUFNMUM
 ABGHHGBA / NFUFNMUM
 ADGFHEFG / NFUFNMUM
 ADEFHGFE / NFUFNMUM
 ADGHHGDA / NFUFNMUM
 ADEHHEDA / NFUFNMUM
 ADCBHEBC / NFUFNMUM
 ADCBHGBC / NFUFNMUM
 ADCBHEFG / NFUFNMUM
 ADBCHEGF / NFUFNMUM
 AFGHHGFA / NFUFNMUM
 AFEDHGDE / NFUFNMUM
 AFCBHGBC / NFUFNMUM
 AFEBHGDC / NFUFNMUM
 AFCDHGBE / NFUFNMUM
 AFDEHGCB / NFUFNMUM
 AFEDHGBC / NFUFNMUM
 AFDCHGCD / NFUFNMUM
 AFEBHGBE / NFUFNMUM
 ADCBBCDA / NFUFUMNM
 ADEFBCFE / NFUFUMNM
 ADEHBCFG / NFUFUMNM
 ADFEBCGH / NFUFUMNM
 ADFGBCGF / NFUFUMNM
 ADEFBCHG / NFUFUMNM
 ADEHBCHE / NFUFUMNM
 ADGHBCHG / NFUFUMNM
 ADGFBCHE / NFUFUMNM
 AFEDBCDE / NFUFUMNM
 AFCBBCFA / NFUFUMNM
 AFGHBCHG / NFUFUMNM
 AFGHBEHG / NFUFUMNM
 AFEBBEFA / NFUFUMNM
 AFCDBEDC / NFUFUMNM
 AFGHBEDC / NFUFUMNM
 AFHGBECD / NFUFUMNM
 AHEDBCDE / NFUFUMNM
 AHCBBCHA / NFUFUMNM
 AHEBBEHA / NFUFUMNM
 AHCDBEDC / NFUFUMNM
 AHCDBGDC / NFUFUMNM
 ABCDDCBA / NFUFUMNM
 ABFEDCEF / NFUFUMNM
 ABFGDCEH / NFUFUMNM
 ABGHDCFE / NFUFUMNM
 ABGFDCFG / NFUFUMNM
 ABHGDCEF / NFUFUMNM
 ABHEDCEH / NFUFUMNM
 ABHGDCGH / NFUFUMNM
 ABHEDCGF / NFUFUMNM
 AFGHDEHG / NFUFUMNM
 AFEDDEFA / NFUFUMNM
 AFBCDECB / NFUFUMNM
 AHEDDEHA / NFUFUMNM
 AHBCDECB / NFUFUMNM
 AHBCDGCB / NFUFUMNM
 AHBGDECF / NFUFUMNM
 ABCFFCBA / NFUFUMNM
 ABEDFCDE / NFUFUMNM
 ABHGFCGH / NFUFUMNM
 ABCDFEDC / NFUFUMNM
 ABCHFEDG / NFUFUMNM
 ABEFFEBA / NFUFUMNM
 ABHGFEGH / NFUFUMNM
 ADEFFEDA / NFUFUMNM
 ADHGFEGH / NFUFUMNM
 ADCBFEBC / NFUFUMNM
 AHDEFGED / NFUFUMNM
 AHBCFGCB / NFUFUMNM
 AHDCFGEB / NFUFUMNM
 AHBEFGCD / NFUFUMNM
 AHCBFGDE / NFUFUMNM
 AHBCFGED / NFUFUMNM
 AHCDFGDC / NFUFUMNM
 AHBEFGEB / NFUFUMNM
 ABCHHCBA / NFUFUMNM
 ABEDHCDE / NFUFUMNM
 ABEFHCDG / NFUFUMNM
 ABFGHCED / NFUFUMNM
 ABFEHCEF / NFUFUMNM
 ABGFHCDE / NFUFUMNM
 ABGDHCDG / NFUFUMNM
 ABGFHCFG / NFUFUMNM
 ABGDHCFE / NFUFUMNM
 ABCDHEDC / NFUFUMNM
 ABEHHEBA / NFUFUMNM
 ABGFHEFG / NFUFUMNM
 ABCDHGDC / NFUFUMNM
 ABCFHGDE / NFUFUMNM
 ABCDHGFE / NFUFUMNM
 ABCFHGFC / NFUFUMNM
 ABDCHGEF / NFUFUMNM
 ABDEHGED / NFUFUMNM
 ABEFHGFE / NFUFUMNM
 ABEDHGFC / NFUFUMNM
 ABGHHGBA / NFUFUMNM
 ADGFHEFG / NFUFUMNM
 ADEFHGFE / NFUFUMNM
 ADGHHGDA / NFUFUMNM
 ADEHHEDA / NFUFUMNM
 ADCBHEBC / NFUFUMNM
 ADCBHGBC / NFUFUMNM
 ADCBHEFG / NFUFUMNM
 ADBCHEGF / NFUFUMNM
 AFGHHGFA / NFUFUMNM
 AFEDHGDE / NFUFUMNM
 AFCBHGBC / NFUFUMNM
 AFEBHGDC / NFUFUMNM
 AFCDHGBE / NFUFUMNM
 AFDEHGCB / NFUFUMNM
 AFEDHGBC / NFUFUMNM
 AFDCHGCD / NFUFUMNM
 AFEBHGBE / NFUFUMNM
 Total explicit: 1692
 Total raw: 153216

With mnemo not included:
 ADCBBCDA
 ADEFBCFE
 ADEHBCFG
 ADFEBCGH
 ADFGBCGF
 ADEFBCHG
 ADEHBCHE
 ADGHBCHG
 ADGFBCHE
 AFEDBCDE
 AFCBBCFA
 AFGHBCHG
 AFGHBEHG
 AFEBBEFA
 AFCDBEDC
 AFGHBEDC
 AFHGBECD
 AHEDBCDE
 AHCBBCHA
 AHEBBEHA
 AHCDBEDC
 AHCDBGDC
 ABCDDCBA
 ABFEDCEF
 ABFGDCEH
 ABGHDCFE
 ABGFDCFG
 ABHGDCEF
 ABHEDCEH
 ABHGDCGH
 ABHEDCGF
 AFGHDEHG
 AFEDDEFA
 AFBCDECB
 AHEDDEHA
 AHBCDECB
 AHBCDGCB
 AHBGDECF
 ABCFFCBA
 ABEDFCDE
 ABHGFCGH
 ABCDFEDC
 ABCHFEDG
 ABEFFEBA
 ABHGFEGH
 ADEFFEDA
 ADHGFEGH
 ADCBFEBC
 AHDEFGED
 AHBCFGCB
 AHDCFGEB
 AHBEFGCD
 AHCBFGDE
 AHBCFGED
 AHCDFGDC
 AHBEFGEB
 ABCHHCBA
 ABEDHCDE
 ABEFHCDG
 ABFGHCED
 ABFEHCEF
 ABGFHCDE
 ABGDHCDG
 ABGFHCFG
 ABGDHCFE
 ABCDHEDC
 ABEHHEBA
 ABGFHEFG
 ABCDHGDC
 ABCFHGDE
 ABCDHGFE
 ABCFHGFC
 ABDCHGEF
 ABDEHGED
 ABEFHGFE
 ABEDHGFC
 ABGHHGBA
 ADGFHEFG
 ADEFHGFE
 ADGHHGDA
 ADEHHEDA
 ADCBHEBC
 ADCBHGBC
 ADCBHEFG
 ADBCHEGF
 AFGHHGFA
 AFEDHGDE
 AFCBHGBC
 AFEBHGDC
 AFCDHGBE
 AFDEHGCB
 AFEDHGBC
 AFDCHGCD
 AFEBHGBE
 Total explicit: 94
 Total raw: 153216

 Process finished with exit code 0
*/